stages:
  - docker_login
  - docker_build
  - docker_publish

#-----------docker_login-----------

docker_login:
  stage: docker_login
  script:
    - DOCKER_LOGIN_COMMAND=$(aws ecr get-login --region eu-west-1 --no-include-email)
    - $DOCKER_LOGIN_COMMAND
  tags:
    - docker

docker_build:
  stage: docker_build
  variables:
    DOCKER_IMAGE_NAME: "colour_changer"
  script:
    - docker build . -t $DOCKER_IMAGE_NAME
  tags:
    - docker

docker_publish:
  stage: docker_publish
  variables:
    DOCKER_IMAGE_NAME: "colour_changer"
  script:
    - docker tag $DOCKER_IMAGE_NAME:latest 364843010988.dkr.ecr.eu-west-1.amazonaws.com/$DOCKER_IMAGE_NAME:latest
    - docker push 364843010988.dkr.ecr.eu-west-1.amazonaws.com/$DOCKER_IMAGE_NAME:latest