stages:
  - docker_login
  - docker_build
  - docker_publish
  - deploy

#-----------docker_login-----------

docker_login:
  stage: docker_login
  script:
    - DOCKER_LOGIN_COMMAND=$(aws ecr get-login --region eu-west-1 --no-include-email)
    - $DOCKER_LOGIN_COMMAND
    - docker login --username=$DOCKER_HUB_NAME --password=$DOCKER_HUB_PASSWORD
  tags:
    - docker

#-----------docker_build-----------

docker_build:
  stage: docker_build
  variables:
    DOCKER_IMAGE_NAME: "colour_changer"
  script:
    - docker build . -t $DOCKER_IMAGE_NAME
  tags:
    - docker

#-----------docker_publish-----------

docker_publish:
  stage: docker_publish
  variables:
    DOCKER_IMAGE_NAME: "colour_changer"
  script:
    - docker tag $DOCKER_IMAGE_NAME:latest 364843010988.dkr.ecr.eu-west-1.amazonaws.com/$DOCKER_IMAGE_NAME:latest
    - docker push 364843010988.dkr.ecr.eu-west-1.amazonaws.com/$DOCKER_IMAGE_NAME:latest
    - docker tag $DOCKER_IMAGE_NAME:latest aidanoflann/$DOCKER_IMAGE_NAME
    - docker push aidanoflann/$DOCKER_IMAGE_NAME
  tags:
    - docker

#-----------deploy-----------

deploy_to_ecs:
  stage: deploy
  script:
    # Create new task definition
    - JSON_CONTENT="$(cat deployment/task_definition.json)"
    - JSON_CONTENT="${JSON_CONTENT/<REDIS_PORT>/$APP_REDIS_PORT}"
    - JSON_CONTENT="${JSON_CONTENT/<REDIS_URL>/$APP_REDIS_URL}"
    - NEW_TD=$(aws ecs register-task-definition --family colour_changer_port_range --container-definitions "$JSON_CONTENT")
    - echo $NEW_TD > new_td.json

    # Determine the new revision id
    - LATEST_TD_ID=$(python deployment/get_json_entry.py --json_filename new_td.json --arg_path "taskDefinition,revision")

    # Update the service to use the new task definition
    - aws ecs update-service --service colour_changer_port_range --task-definition colour_changer_port_range:$LATEST_TD_ID

    # Deregister the old task definition
    - aws ecs deregister-task-definition --task-definition colour_changer_port_range:$((LATEST_TD_ID - 1))
  tags:
    - docker
  when: manual